import type { Metadata } from "next";
import "@/app/globals.css";

// components
import Sidebar from "@/app/(dashboard)/_components/sidebar";
import Header from "@/app/(dashboard)/_components/header";

export const metadata: Metadata = {
  title: "meetrix | dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="relative flex w-full">
          <Sidebar />
          <div className="w-full">
            <Header />
            <div className="p-4">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}

/**
 *
 * dashboard
 * events
 * meetings
 * availability
 *
 */
